name: neo4dart
version: 0.0.1
description: Driver for neo4j
homepage: https://github.com/matth3o/neo4dart
environment:
  sdk: '>=1.0.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
  logging: ">=0.9.2 <0.10.0"
  http: ">=0.11.1+1 <0.12.0"
dev_dependencies:
  unittest: '>=0.11.0'
  matcher: '>=0.10.0'
  mock: ">=0.11.0+2 <0.12.0"
